-- Add pfp4_proposals JSONB column to votation_sessions
-- Stores per-student place proposals for PFP4 voting
-- Format: { "user_id_1": ["placeId1", "placeId2", ...], "user_id_2": [...] }
ALTER TABLE votation_sessions ADD COLUMN IF NOT EXISTS pfp4_proposals JSONB DEFAULT NULL;

COMMENT ON COLUMN votation_sessions.pfp4_proposals IS 'PFP4 per-student place proposals. Map of userId -> [placeIds]. Generated by admin algo, used to filter places in student vote view.';
