// Routes PFP Management & Formation Pratique Physio
export default [
  // PFP Management
  { path: '/management_pfpencours', component: () => import('@/views/admin/pfp/ManagementPFPEnCoursView.vue'), name: 'ManagementPFPEnCoursView', meta: { requiresAuth: true, need: 'admin' } },
  { path: '/management_votation_prioritaire', component: () => import('@/views/admin/pfp/ManagementVotationPrioritaireView.vue'), name: 'ManagementVotationPrioritaire', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/management_offre', component: () => import('@/views/admin/pfp/ManagementOffreView.vue'), name: 'ManagementOffre', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/management_votation_etudiants', component: () => import('@/views/admin/pfp/VotationEtudiantsView.vue'), name: 'VotationEtudiants', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/places_asssigned', component: () => import('@/views/admin/pfp/PlacesAssignedView.vue'), name: 'PlacesAssigned', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/management_place', component: () => import('@/views/admin/pfp/ManagementPlacesView.vue'), name: 'ManagementPlaces', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/management_repondant', component: () => import('@/views/admin/pfp/ManagementRepondantView.vue'), name: 'ManagementRepondant', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/validation-places', component: () => import('@/views/admin/pfp/PlacesAssignmentView.vue'), name: 'ValidationPlaces', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/validation-pfp', component: () => import('@/views/admin/pfp/ValidationPFP.vue'), name: 'ValidationPFP', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/gantt', component: () => import('@/views/admin/pfp/GanttPFPView.vue'), name: 'GanttPFP', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/validate-pfp1a', component: () => import('@/views/admin/pfp/ValidatePFP1AView.vue'), name: 'ValidatePFP1A', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/info_repondant', component: () => import('@/views/admin/pfp/InfoRepondantView.vue'), name: 'InfoRepondant', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/result_preview_votation', component: () => import('@/views/admin/pfp/ResultPreviewVotationView.vue'), name: 'ResultPreviewVotation', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/pfp/cohort-stats', component: () => import('@/views/admin/pfp/PfpCohortStatsView.vue'), name: 'PfpCohortStats', meta: { requiresAuth: true, need: ['admin', 'page1.access'] } },

  // Aliases propres pour les anciennes routes (redirigent vers les mêmes composants)
  { path: '/admin/formation-pratique/enseignants', component: () => import('@/views/admin/users/TeacherListView.vue'), name: 'FPEnseignants', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/gestion-offres', component: () => import('@/views/admin/pfp/ManagementOffreView.vue'), name: 'FPGestionOffres', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/votation-lese', component: () => import('@/views/admin/pfp/ManagementVotationPrioritaireView.vue'), name: 'FPVotationLese', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/places-assignees', component: () => import('@/views/admin/pfp/PlacesAssignedView.vue'), name: 'FPPlacesAssignees', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/management-places', component: () => import('@/views/admin/pfp/ManagementPlacesView.vue'), name: 'FPManagementPlaces', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/validation-places', component: () => import('@/views/admin/pfp/PlacesAssignmentView.vue'), name: 'FPValidationPlaces', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/validation-pfp', component: () => import('@/views/admin/pfp/ValidationPFP.vue'), name: 'FPValidationPFP', meta: { requiresAuth: true, need: 'page1.access' } },

  // Formation Pratique Physio
  { path: '/admin/formation-pratique/dashboard', redirect: '/admin/dashboard-pfp' },
  { path: '/admin/formation-pratique/etudiants', component: () => import('@/views/admin/formation-pratique/EtudiantsViewPHYFP.vue'), name: 'FPEtudiants', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/institutions', component: () => import('@/views/admin/formation-pratique/InstitutionsViewPHYFP.vue'), name: 'FPInstitutions', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/praticiens-formateur', component: () => import('@/views/admin/formation-pratique/PraticiensFormateurViewPHYFP.vue'), name: 'FPPraticiensFormateur', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/places', component: () => import('@/views/admin/formation-pratique/PlacesViewPHYFP.vue'), name: 'FPPlaces', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/correction-pfp1-ba24', component: () => import('@/views/admin/formation-pratique/CorrectionPfp1Ba24View.vue'), name: 'FPCorrectionPfp1Ba24', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/profil-etudiants', component: () => import('@/views/admin/formation-pratique/ProfilEtudiantsViewPHYFP.vue'), name: 'FPProfilEtudiants', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/profil-repondant', component: () => import('@/views/admin/formation-pratique/ProfileRepondantView.vue'), name: 'ProfileRepondant', meta: { requiresAuth: true } },
  { path: '/admin/formation-pratique/management-repondant-signature', component: () => import('@/views/admin/formation-pratique/ManagementRepondantVotationViewPHYFP.vue'), name: 'ManagementRepondantSignature', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/assign-repondants-ba25', component: () => import('@/views/admin/AssignRepondantsView.vue'), name: 'AssignRepondantsBA25Static', meta: { requiresAuth: true, need: 'admin' } },
  { path: '/admin/formation-pratique/gantt-pfp', component: () => import('@/views/admin/pfp/GanttPFPView.vue'), name: 'FPGanttPFP', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/admin-secretariat', component: () => import('@/views/admin/formation-pratique/AdminSecretariatViewPHYFP.vue'), name: 'FPAdminSecretariat', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/admin-secretariat-general', component: () => import('@/views/admin/formation-pratique/AdminSecretariatGeneralViewPHYFP.vue'), name: 'FPAdminSecretariatGeneral', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/management-repondant-cpt', component: () => import('@/views/admin/formation-pratique/ManagementRepondantCPTViewPHYFP.vue'), name: 'FPManagementRepondantCPT', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/management-feuille-charge-cpt', component: () => import('@/views/admin/formation-pratique/ManagementFeuilleDeChargeRepondantCPTViewPHYFP.vue'), name: 'FPManagementFeuilleChargeCPT', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/offre-place', component: () => import('@/views/admin/pfp/ManagementOffreView.vue'), name: 'FPOffrePlace', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/preview-pfp', component: () => import('@/views/admin/pfp/ResultPreviewVotationView.vue'), name: 'FPPreviewPFP', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/resultat-votation-prioritaire', component: () => import('@/views/admin/pfp/ManagementVotationPrioritaireView.vue'), name: 'FPResultatVotationPrioritaire', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/resultat-votation-pfp', component: () => import('@/views/admin/pfp/ResultPreviewVotationView.vue'), name: 'FPResultatVotationPFP', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/management-repondant-votation', component: () => import('@/views/admin/formation-pratique/ManagementRepondantVotationViewPHYFP.vue'), name: 'FPManagementRepondantVotation', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/valider-echec-pfp', component: () => import('@/views/admin/pfp/ValidationPFP.vue'), name: 'FPValiderEchecPFP', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/votation-prioritaire', component: () => import('@/views/admin/formation-pratique/VotationPrioritaireViewPHYFP.vue'), name: 'FPVotationPrioritaire', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/votation-pfp', component: () => import('@/views/admin/formation-pratique/VotationPFPViewPHYFP.vue'), name: 'FPVotationPFP', meta: { requiresAuth: true, need: 'page1.access' } },

  // Secrétariat FP
  { path: '/admin/formation-pratique/secretariat/verification-criteres', component: () => import('@/views/admin/formation-pratique/secretariat/VerificationCriteresEtudiants.vue'), name: 'VerificationCriteresEtudiants', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/secretariat/suivi-institutions', component: () => import('@/views/admin/formation-pratique/secretariat/SuiviInstitutions.vue'), name: 'SuiviInstitutions', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/secretariat/couverture-stages', component: () => import('@/views/admin/formation-pratique/secretariat/CouvertureStages.vue'), name: 'CouvertureStages', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/secretariat/suivi-offres-institutions', component: () => import('@/views/admin/formation-pratique/secretariat/SuiviOffresInstitutions.vue'), name: 'SuiviOffresInstitutions', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/secretariat/tableau-offres', component: () => import('@/views/admin/formation-pratique/secretariat/TableauRecapitulatifOffres.vue'), name: 'TableauRecapitulatifOffres', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/secretariat/recap-pfp-notes', component: () => import('@/views/admin/formation-pratique/secretariat/RecapPFPNotes.vue'), name: 'RecapPFPNotes', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/secretariat/recap-cpt-evaluation', component: () => import('@/views/admin/formation-pratique/secretariat/RecapCPTEvaluation.vue'), name: 'RecapCPTEvaluation', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/secretariat/suivi-cas-particuliers', component: () => import('@/views/admin/formation-pratique/secretariat/SuiviCasParticuliers.vue'), name: 'SuiviCasParticuliers', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/secretariat/alertes', component: () => import('@/views/admin/formation-pratique/secretariat/AlertesDashboard.vue'), name: 'AlertesDashboard', meta: { requiresAuth: true, need: 'page1.access' } },
  { path: '/admin/formation-pratique/secretariat/vue-ensemble', component: () => import('@/views/admin/formation-pratique/secretariat/VueDEnsembleFP.vue'), name: 'VueDEnsembleFP', meta: { requiresAuth: true, need: 'page1.access' } },
]
