/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'intro',
    'getting-started',
    'domains/priorite-extension-soins-infirmiers-et-profil-etudiant',
    {
      type: 'category',
      label: 'Vision système',
      collapsed: false,
      items: [
        'architecture',
        'system/overview',
        'system/recovery-checklist',
        'system/project-structure',
      ],
    },
    {
      type: 'category',
      label: 'Frontend',
      collapsed: false,
      items: [
        'frontend/bootstrap',
        'frontend/component-library-overview',
        'frontend/component-library-layout',
        'frontend/component-library-common-ui',
        'frontend/component-library-admin',
        'frontend/component-library-social-media',
        'frontend/component-library-critical-components',
        'frontend/routing',
        'frontend/data-refresh-pattern',
        'frontend/router-modules',
        'frontend/route-catalog',
        'frontend/state',
        'frontend/critical-stores',
        'frontend/stores-services-map',
        'frontend/services-catalog',
        'frontend/view-store-service-matrix',
        'frontend/route-to-data-matrix',
        'frontend/ui',
        'frontend/pwa',
      ],
    },
    {
      type: 'category',
      label: 'Auth, rôles et sécurité',
      collapsed: false,
      items: [
        'auth/overview',
        'auth/auth-routing-lifecycle',
        'auth/permission-model',
        'auth/security-services-legacy',
        'security/roles',
        'security/route-guards',
        'security/supabase-rls',
      ],
    },
    {
      type: 'category',
      label: 'Données et backends',
      collapsed: false,
      items: [
        'data/overview',
        'data/critical-tables',
        'data/rpc-and-sql-surface',
        'data/schema-supabase',
        'data/migrations-catalog',
        'data/migration-firebase-supabase',
        'data/multi-system-router',
        'backend/overview',
        'backend/endpoints-catalog',
        'backend/frontend-backend-traceability',
        'backend/routes-map',
        'backend/active-vs-legacy',
        'backend/firebase/overview',
        'backend/firebase/database',
        'backend/firebase/storage',
        'backend/firebase/auth',
        'backend/supabase/overview',
        'backend/supabase/services',
        'backend/supabase/rls',
        'backend/supabase/migrations',
      ],
    },
    {
      type: 'category',
      label: 'Domaines métier',
      collapsed: false,
      items: [
        'domains/formation-pratique',
        'domains/formation-pratique-fonctionnel',
        'domains/formation-pratique-traceability',
        'domains/pfp-services-deep-dive',
        'domains/formation-pratique-flows',
        'domains/planning-soins',
        'domains/social-gamification',
        'domains/gamification-service-deep-dive',
        'domains/votation-algorithm',
        'domains/votation-systeme-complet',
        'domains/votation-priority-score',
        'domains/multi-filiere-si-phy',
        'domains/ui-ownership-map',
        'apps/overview',
        'media/modules',
        'media/vimeo-config',
        'media/media-service',
      ],
    },
    {
      type: 'category',
      label: 'Exploitation',
      collapsed: false,
      items: [
        'ops/development',
        'ops/deployment',
        'ops/vps-topology',
        'ops/vps-operations',
        'ops/runbook',
        'testing/overview',
        'testing/scripts',
        'testing/diagnostic-tools',
      ],
    },
    {
      type: 'category',
      label: 'Contribution',
      collapsed: false,
      items: [
        'contrib/workflow',
        'contrib/conventions',
        'contrib/eslint-prettier',
        'contrib/docs-style-guide',
        'contrib/github',
      ],
    },
    'priorites-developpement',
    'roadmap',
    'changelog',
  ],
};

module.exports = sidebars;
