-- Table pour le suivi des cas particuliers des étudiants
-- Stocke les commentaires et couleurs pour chaque PFP par étudiant

CREATE TABLE IF NOT EXISTS public.suivi_cas_particuliers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  pfp_field text NOT NULL CHECK (pfp_field IN ('pfp1', 'pfp1_prime', 'pfp2', 'pfp2_prime', 'pfp3', 'pfp3_prime', 'pfp4', 'pfp4_prime')),
  couleur text NOT NULL DEFAULT 'blanc' CHECK (couleur IN ('blanc', 'vert', 'orange', 'rouge', 'noir')),
  commentaire text,
  visible boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  UNIQUE(user_id, pfp_field)
);

-- Index pour optimiser les recherches
CREATE INDEX IF NOT EXISTS idx_suivi_cas_user_id ON public.suivi_cas_particuliers(user_id);
CREATE INDEX IF NOT EXISTS idx_suivi_cas_pfp_field ON public.suivi_cas_particuliers(pfp_field);
CREATE INDEX IF NOT EXISTS idx_suivi_cas_visible ON public.suivi_cas_particuliers(visible);

-- Fonction pour mettre à jour automatiquement updated_at
CREATE OR REPLACE FUNCTION public.update_suivi_cas_particuliers_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger pour mettre à jour updated_at
DROP TRIGGER IF EXISTS trigger_update_suivi_cas_particuliers_updated_at ON public.suivi_cas_particuliers;
CREATE TRIGGER trigger_update_suivi_cas_particuliers_updated_at
  BEFORE UPDATE ON public.suivi_cas_particuliers
  FOR EACH ROW
  EXECUTE FUNCTION public.update_suivi_cas_particuliers_updated_at();

-- Permissions RLS (Row Level Security)
ALTER TABLE public.suivi_cas_particuliers ENABLE ROW LEVEL SECURITY;

-- Policy pour permettre la lecture à tous les utilisateurs authentifiés
CREATE POLICY "Allow read for authenticated users" ON public.suivi_cas_particuliers
  FOR SELECT
  TO authenticated
  USING (true);

-- Policy pour permettre l'insertion aux utilisateurs authentifiés
CREATE POLICY "Allow insert for authenticated users" ON public.suivi_cas_particuliers
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Policy pour permettre la mise à jour aux utilisateurs authentifiés
CREATE POLICY "Allow update for authenticated users" ON public.suivi_cas_particuliers
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Policy pour permettre la suppression aux utilisateurs authentifiés
CREATE POLICY "Allow delete for authenticated users" ON public.suivi_cas_particuliers
  FOR DELETE
  TO authenticated
  USING (true);

-- Commentaires sur la table et les colonnes
COMMENT ON TABLE public.suivi_cas_particuliers IS 'Suivi des cas particuliers des étudiants avec commentaires et couleurs par PFP';
COMMENT ON COLUMN public.suivi_cas_particuliers.user_id IS 'ID de l''étudiant';
COMMENT ON COLUMN public.suivi_cas_particuliers.pfp_field IS 'Champ PFP (pfp1, pfp1_prime, pfp2, pfp2_prime, pfp3, pfp3_prime, pfp4, pfp4_prime)';
COMMENT ON COLUMN public.suivi_cas_particuliers.couleur IS 'Couleur du statut (blanc, vert, orange, rouge, noir)';
COMMENT ON COLUMN public.suivi_cas_particuliers.commentaire IS 'Commentaire sur le cas particulier';
COMMENT ON COLUMN public.suivi_cas_particuliers.visible IS 'Visibilité de l''étudiant dans la liste';
