-- Script pour diagnostiquer et recréer la table suivi_cas_particuliers dans le bon schéma

-- 1. Vérifier où se trouve la table actuelle
SELECT schemaname, tablename 
FROM pg_tables 
WHERE tablename = 'suivi_cas_particuliers';

-- 2. Supprimer la table si elle existe dans un autre schéma
DROP TABLE IF EXISTS public.suivi_cas_particuliers CASCADE;
DROP TABLE IF EXISTS suivi_cas_particuliers CASCADE;

-- 3. Créer la table dans le schéma public
CREATE TABLE public.suivi_cas_particuliers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  pfp_field text NOT NULL CHECK (pfp_field IN ('pfp1', 'pfp1_prime', 'pfp2', 'pfp2_prime', 'pfp3', 'pfp3_prime', 'pfp4', 'pfp4_prime', 'info_etudiant')),
  couleur text NOT NULL DEFAULT 'blanc' CHECK (couleur IN ('blanc', 'vert', 'orange', 'rouge', 'noir')),
  commentaire text,
  visible boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(user_id, pfp_field)
);

-- 4. Créer les index
CREATE INDEX idx_suivi_cas_user_id ON public.suivi_cas_particuliers(user_id);
CREATE INDEX idx_suivi_cas_pfp_field ON public.suivi_cas_particuliers(pfp_field);
CREATE INDEX idx_suivi_cas_visible ON public.suivi_cas_particuliers(visible);

-- 5. Créer le trigger pour updated_at
CREATE OR REPLACE FUNCTION public.update_suivi_cas_particuliers_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_update_suivi_cas_particuliers_updated_at ON public.suivi_cas_particuliers;
CREATE TRIGGER trigger_update_suivi_cas_particuliers_updated_at
  BEFORE UPDATE ON public.suivi_cas_particuliers
  FOR EACH ROW
  EXECUTE FUNCTION public.update_suivi_cas_particuliers_updated_at();

-- 6. Désactiver RLS pour simplifier (vous pourrez le réactiver plus tard)
ALTER TABLE public.suivi_cas_particuliers DISABLE ROW LEVEL SECURITY;

-- 7. Donner les permissions nécessaires
GRANT ALL ON public.suivi_cas_particuliers TO authenticated;
GRANT SELECT ON public.suivi_cas_particuliers TO anon;

-- 8. Vérifier que la table est bien créée dans le schéma public
SELECT schemaname, tablename, tableowner 
FROM pg_tables 
WHERE tablename = 'suivi_cas_particuliers' AND schemaname = 'public';

-- 9. Vérifier les permissions
SELECT grantee, privilege_type 
FROM information_schema.role_table_grants 
WHERE table_name = 'suivi_cas_particuliers' AND table_schema = 'public';

-- 10. Forcer le rafraîchissement du cache de schéma
NOTIFY pgrst, 'reload schema';

-- Message de confirmation
SELECT '✅ Table suivi_cas_particuliers créée avec succès dans le schéma public!' as status;
